name: "🚀 DB Prisma Beta Access Request"
description: Apply for the Xirang Program to get your activation code.
title: "[Beta Request]: "
labels: ["beta-application"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the Xirang Program!
        To help us provide better support, please fill out the details below.
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Where should we send your activation code?
      placeholder: example@gmail.com
    validations:
      required: true
  - type: dropdown
    id: use-case
    attributes:
      label: Primary Use Case
      options:
        - AI Corpus Extraction
        - Database Migration & Dialect Conversion
        - High-Concurrency Traffic Interception
        - Security Auditing & Forensics
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Technical Environment
      description: e.g., Windows Server 2022, MySQL 8.0, 10k QPS...
